// ============================================================
//  MAAYA Enterprises — Central Data File
//  Yahan se saara data aata hai — courses, nav, footer sab
// ============================================================

// ── Navigation Links ────────────────────────────────────────
export const NAV_LINKS = [
  { name: "Home",    path: "/" },
  { name: "Courses", path: "/courses" },
  { name: "About",   path: "/about" },
  { name: "Contact", path: "/contact" },
];

// ── Contact Info (Footer & Contact Page) ────────────────────
export const CONTACT_INFO = {
  address:   "Panchami Heights, 204, College Rd, near Moti Talav, Sawantwadi, Maharashtra 416510",
  phone:     "919420277373",
  email:     "education.maaya@gmail.com",
  whatsapp:  "919420277373",
  mapLink:   "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d491154.2530500439!2d73.56413236989431!3d15.901598384411846!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bbff55e1a060675%3A0x4f9b888315408d04!2sMAAYA%20ENTERPRISES!5e0!3m2!1sen!2sin!4v1777992900325!5m2!1sen!2sin",
};

// ── Social Links ─────────────────────────────────────────────
export const SOCIAL_LINKS = {
  facebook:  "https://www.facebook.com/share/1BVxQs32kg/",
  instagram: "https://www.instagram.com/maaya.skill/",
  youtube:   "/* TODO: YouTube channel URL */",
  twitter:   "/* TODO: Twitter/X URL */",
};

// ── Course Categories ────────────────────────────────────────
export const CATEGORIES = [
  "All",
  "IT & Computer",
  "Business",
  "Skill Development",
  "Language",
  "Design",
  "Finance",
];

// ── 20 Courses Data ─────────────────────────────────────────
// Har course mein yeh fields hain:
//   id, title, category, level, duration, students,
//   rating, price, originalPrice, isFree, isPremium,
//   thumbnail (color gradient class), tags, badge,
//   description, overview, highlights, stats, syllabus,
//   eligibility, features
// ─────────────────────────────────────────────────────────────
export const COURSES = [
  {
    id: 1,
    title: "MS-CIT",
    subtitle: "Maharashtra State Certificate in Information Technology",
    category: "IT & Computer",
    level: "Beginner",
    duration: "6 Months",
    students: 52000,
    rating: 4.8,
    reviews: 2100,
    price: 4500,
    originalPrice: 6000,
    isFree: false,
    isPremium: false,
    badge: "Most Popular",
    gradient: "grad-blue",
    icon: "💻",
    tags: ["MS Office", "Internet", "Email", "Govt. Certified"],
    description: "Maharashtra Govt. certified computer course. Most popular IT certification for government jobs & daily use.",
    overview: "MS-CIT is the most trusted computer literacy program in Maharashtra. /* TODO: Full overview text daalo */",
    highlights: [
      "Industry-relevant curriculum",
      "Govt. recognized certificate",
      "Expert instructors with 10+ years experience",
    ],
    stats: { duration: "3 Months", level: "Beginner", enrolled: "52,000+" },
    syllabus: [
      "Module 1: Computer Basics",
      "Module 2: MS Word",
      "Module 3: MS Excel",
      "Module 4: MS PowerPoint",
      "Module 5: Internet & Email",
      "Module 6: Online Services & e-Governance",
      "/* TODO: More modules daalo */",
    ],
    eligibility: ["8th pass minimum", "No prior computer knowledge needed"],
    features: ["40 hours of classes", "Online + Offline batches", "Government certified", "Job assistance"],
  },
  {
    id: 2,
    title: "KLiC Web Design & Development",
    subtitle: "Build Professional Websites from Scratch",
    category: "IT & Computer",
    level: "Intermediate",
    duration: "4 Months",
    students: 8900,
    rating: 4.7,
    reviews: 890,
    price: 5200,
    originalPrice: 7500,
    isFree: false ,
    isPremium: true,
    badge: "Trending",
    gradient: "grad-purple",
    icon: "🖥️",
    tags: ["HTML", "CSS", "JavaScript", "React"],
    description: "Learn to build modern websites using HTML, CSS, JavaScript and React. Real-world projects included.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Hands-on project-based learning", "Industry mentors", "Portfolio building"],
    stats: { duration: "4 Months", level: "Intermediate", enrolled: "8,900+" },
    syllabus: ["HTML5 Fundamentals", "CSS3 & Flexbox", "JavaScript ES6+", "React Basics", "/* TODO: More add karo */"],
    eligibility: ["Basic computer knowledge", "10th pass minimum"],
    features: ["30+ hours video content", "Live projects", "Certificate", "Placement support"],
  },
  {
    id: 3,
    title: "Tally Prime with GST",
    subtitle: "Complete Accounting & GST Filing Course",
    category: "Business",
    level: "Beginner",
    duration: "3 Months",
    students: 14200,
    rating: 4.6,
    reviews: 1400,
    price: 3800,
    originalPrice: 5500,
    isFree: false,
    isPremium: false,
    badge: "",
    gradient: "grad-green",
    icon: "📊",
    tags: ["Tally", "GST", "Accounting", "Payroll"],
    description: "Master Tally ERP, GST filing, balance sheets and complete accounts management.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Practical accounting training", "GST return filing", "Live project work"],
    stats: { duration: "3 Months", level: "Beginner", enrolled: "14,200+" },
    syllabus: ["Tally Basics", "Voucher Entry", "GST Setup", "Balance Sheet", "/* TODO: More add karo */"],
    eligibility: ["Basic math knowledge", "Commerce background preferred"],
    features: ["20 hours classes", "Practice software", "Certificate", "Job assistance"],
  },
  {
    id: 4,
    title: "Python & Artificial Intelligence",
    subtitle: "AI & ML Fundamentals with Python",
    category: "IT & Computer",
    level: "Advanced",
    duration: "5 Months",
    students: 4500,
    rating: 4.9,
    reviews: 450,
    price: 8000,
    originalPrice: 12000,
    isFree: false,
    isPremium: true,
    badge: "Hot",
    gradient: "grad-orange",
    icon: "🤖",
    tags: ["Python", "AI", "Machine Learning", "Data Science"],
    description: "Learn Python programming, AI fundamentals and build real ML models from scratch.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Real ML projects", "Industry mentors", "Career in AI"],
    stats: { duration: "5 Months", level: "Advanced", enrolled: "4,500+" },
    syllabus: ["Python Basics", "Data Structures", "NumPy & Pandas", "Machine Learning", "/* TODO: More add karo */"],
    eligibility: ["Basic math & logic", "12th pass minimum"],
    features: ["50+ hours content", "Live projects", "AI certificate", "Placement support"],
  },
  {
    id: 5,
    title: "Spoken English & Communication",
    subtitle: "Speak Confidently in Every Situation",
    category: "Language",
    level: "All Levels",
    duration: "2 Months",
    students: 19000,
    rating: 4.7,
    reviews: 1900,
    price: 2500,
    originalPrice: 4000,
    isFree: false,
    isPremium: false,
    badge: "",
    gradient: "grad-teal",
    icon: "🗣️",
    tags: ["Speaking", "Grammar", "Interview Prep", "Presentation"],
    description: "Improve English speaking, grammar and interview communication skills.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Daily speaking practice", "Mock interviews", "Personality development"],
    stats: { duration: "2 Months", level: "All Levels", enrolled: "19,000+" },
    syllabus: ["Basic Grammar", "Pronunciation", "Conversation Practice", "Interview Skills", "/* TODO: More add karo */"],
    eligibility: ["Basic English reading ability"],
    features: ["Daily live sessions", "Recorded classes", "Certificate", "Group practice"],
  },
  {
    id: 6,
    title: "Fashion Design & Tailoring",
    subtitle: "From Beginner to Professional Designer",
    category: "Skill Development",
    level: "Beginner",
    duration: "6 Months",
    students: 7800,
    rating: 4.5,
    reviews: 780,
    price: 3200,
    originalPrice: 5000,
    isFree: false,
    isPremium: false,
    badge: "",
    gradient: "grad-pink",
    icon: "✂️",
    tags: ["Pattern Making", "Stitching", "Design", "Entrepreneurship"],
    description: "Learn garment construction, pattern making and start your own tailoring business.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Practical hands-on training", "Entrepreneurship skills", "Women empowerment"],
    stats: { duration: "6 Months", level: "Beginner", enrolled: "7,800+" },
    syllabus: ["Basic Stitching", "Pattern Making", "Blouse & Salwar", "Saree Designs", "/* TODO: More add karo */"],
    eligibility: ["No prior experience needed", "Age 14+ preferred"],
    features: ["Practical classes", "Material provided", "Certificate", "Business guidance"],
  },
  {
    id: 7,
    title: "Digital Marketing",
    subtitle: "Master SEO, Social Media & Google Ads",
    category: "Business",
    level: "Intermediate",
    duration: "3 Months",
    students: 6200,
    rating: 4.6,
    reviews: 620,
    price: 5500,
    originalPrice: 8000,
    isFree: false,
    isPremium: true,
    badge: "New",
    gradient: "grad-orange",
    icon: "📱",
    tags: ["SEO", "Social Media", "Google Ads", "Content Marketing"],
    description: "Learn digital marketing strategies to grow any business online.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Live campaign projects", "Google Ads certification prep", "Social media mastery"],
    stats: { duration: "3 Months", level: "Intermediate", enrolled: "6,200+" },
    syllabus: ["SEO Basics", "Social Media Marketing", "Google Ads", "Email Marketing", "/* TODO: More add karo */"],
    eligibility: ["Basic internet knowledge", "10th pass minimum"],
    features: ["Live ad campaigns", "Tools access", "Certificate", "Freelancing guidance"],
  },
  {
    id: 8,
    title: "MS Office Mastery",
    subtitle: "Word, Excel, PowerPoint — Complete Course",
    category: "IT & Computer",
    level: "Beginner",
    duration: "2 Months",
    students: 23000,
    rating: 4.5,
    reviews: 2300,
    price: 1800,
    originalPrice: 3000,
    isFree: false,
    isPremium: false,
    badge: "",
    gradient: "grad-blue",
    icon: "📝",
    tags: ["MS Word", "MS Excel", "PowerPoint", "Office Skills"],
    description: "Complete Microsoft Office course — Word, Excel, PowerPoint for office & job use.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Practical exercises", "Job-ready skills", "Quick completion"],
    stats: { duration: "2 Months", level: "Beginner", enrolled: "23,000+" },
    syllabus: ["MS Word", "MS Excel", "MS PowerPoint", "MS Access Basics", "/* TODO: More add karo */"],
    eligibility: ["Basic computer knowledge"],
    features: ["20+ hours", "Practice files", "Certificate", "Job tips"],
  },
  {
    id: 9,
    title: "Graphic Design with Photoshop",
    subtitle: "Create Stunning Visuals Professionally",
    category: "Design",
    level: "Beginner",
    duration: "3 Months",
    students: 5400,
    rating: 4.7,
    reviews: 540,
    price: 4200,
    originalPrice: 6500,
    isFree: false,
    isPremium: false,
    badge: "",
    gradient: "grad-purple",
    icon: "🎨",
    tags: ["Photoshop", "Illustrator", "Logo Design", "Branding"],
    description: "Learn professional graphic design using Adobe Photoshop & Illustrator.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Real client projects", "Portfolio development", "Freelancing income"],
    stats: { duration: "3 Months", level: "Beginner", enrolled: "5,400+" },
    syllabus: ["Photoshop Basics", "Logo Design", "Social Media Graphics", "Print Design", "/* TODO: More add karo */"],
    eligibility: ["Basic computer skills"],
    features: ["30+ hours", "Software provided", "Certificate", "Freelancing guide"],
  },
  {
    id: 10,
    title: "Hardware & Networking",
    subtitle: "Computer Repair, Networking & IT Support",
    category: "IT & Computer",
    level: "Intermediate",
    duration: "4 Months",
    students: 3800,
    rating: 4.4,
    reviews: 380,
    price: 4800,
    originalPrice: 7000,
    isFree: false,
    isPremium: false,
    badge: "",
    gradient: "grad-green",
    icon: "🔧",
    tags: ["Hardware", "Networking", "CCNA", "IT Support"],
    description: "Learn computer hardware repair, network setup and IT support skills.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Practical lab sessions", "Network setup training", "Job in IT support"],
    stats: { duration: "4 Months", level: "Intermediate", enrolled: "3,800+" },
    syllabus: ["Computer Components", "OS Installation", "Network Basics", "Router Setup", "/* TODO: More add karo */"],
    eligibility: ["Basic computer knowledge"],
    features: ["Lab practice", "Tools access", "Certificate", "Job assistance"],
  },
  {
    id: 11,
    title: "Marathi Typing & DTP",
    subtitle: "Desktop Publishing & Marathi/Hindi Typing",
    category: "IT & Computer",
    level: "Beginner",
    duration: "1 Month",
    students: 11000,
    rating: 4.3,
    reviews: 1100,
    price: 1200,
    originalPrice: 2000,
    isFree: false,
    isPremium: false,
    badge: "",
    gradient: "grad-teal",
    icon: "⌨️",
    tags: ["Marathi Typing", "Hindi Typing", "DTP", "PageMaker"],
    description: "Learn fast Marathi & Hindi typing with DTP software for government job exams.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Govt. exam preparation", "Speed typing practice", "DTP certificate"],
    stats: { duration: "1 Month", level: "Beginner", enrolled: "11,000+" },
    syllabus: ["Keyboard Layout", "Marathi Typing", "Hindi Typing", "PageMaker Basics", "/* TODO: More add karo */"],
    eligibility: ["Basic reading in Marathi/Hindi"],
    features: ["Daily practice", "Speed tests", "Certificate", "Exam guidance"],
  },
  {
    id: 12,
    title: "Beautician & Cosmetology",
    subtitle: "Professional Beauty & Skin Care Training",
    category: "Skill Development",
    level: "Beginner",
    duration: "4 Months",
    students: 6100,
    rating: 4.6,
    reviews: 610,
    price: 3500,
    originalPrice: 5500,
    isFree: false,
    isPremium: false,
    badge: "",
    gradient: "grad-pink",
    icon: "💄",
    tags: ["Beauty", "Skin Care", "Makeup", "Hair Styling"],
    description: "Learn professional beauty treatments, skin care and start your own salon.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Practical training", "Salon setup guidance", "Entrepreneurship"],
    stats: { duration: "4 Months", level: "Beginner", enrolled: "6,100+" },
    syllabus: ["Skin Care Basics", "Facial Techniques", "Hair Styling", "Makeup", "/* TODO: More add karo */"],
    eligibility: ["Age 16+ preferred", "No prior experience"],
    features: ["Practical sessions", "Products provided", "Certificate", "Business guidance"],
  },
  {
    id: 13,
    title: "Stock Market & Trading",
    subtitle: "Learn to Invest & Trade in Indian Markets",
    category: "Finance",
    level: "Intermediate",
    duration: "2 Months",
    students: 2900,
    rating: 4.5,
    reviews: 290,
    price: 5000,
    originalPrice: 8000,
    isFree: false,
    isPremium: true,
    badge: "New",
    gradient: "grad-orange",
    icon: "📈",
    tags: ["Stock Market", "Trading", "Mutual Funds", "NSE/BSE"],
    description: "Understand stock market basics, technical analysis and start investing safely.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Live market sessions", "Paper trading practice", "Expert guidance"],
    stats: { duration: "2 Months", level: "Intermediate", enrolled: "2,900+" },
    syllabus: ["Market Basics", "Technical Analysis", "Fundamental Analysis", "Trading Strategies", "/* TODO: More add karo */"],
    eligibility: ["Basic math knowledge", "18+ age"],
    features: ["Live sessions", "Trading tools", "Certificate", "Community access"],
  },
  {
    id: 14,
    title: "Video Editing & YouTube",
    subtitle: "Create & Monetize YouTube Content",
    category: "Design",
    level: "Beginner",
    duration: "2 Months",
    students: 4100,
    rating: 4.6,
    reviews: 410,
    price: 3500,
    originalPrice: 5500,
    isFree: false,
    isPremium: false,
    badge: "",
    gradient: "grad-purple",
    icon: "🎬",
    tags: ["Video Editing", "YouTube", "Premiere Pro", "Content Creation"],
    description: "Learn professional video editing and grow a YouTube channel from scratch.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Real YouTube projects", "Monetization strategies", "Editing tools mastery"],
    stats: { duration: "2 Months", level: "Beginner", enrolled: "4,100+" },
    syllabus: ["Video Basics", "Premiere Pro", "Color Grading", "YouTube SEO", "/* TODO: More add karo */"],
    eligibility: ["Basic computer knowledge"],
    features: ["Software access", "Project-based", "Certificate", "YouTube strategy guide"],
  },
  {
    id: 15,
    title: "E-Commerce & Business",
    subtitle: "Sell Online on Amazon, Flipkart & More",
    category: "Business",
    level: "Beginner",
    duration: "1 Month",
    students: 3300,
    rating: 4.4,
    reviews: 330,
    price: 2800,
    originalPrice: 4500,
    isFree: false,
    isPremium: false,
    badge: "",
    gradient: "grad-green",
    icon: "🛒",
    tags: ["Amazon", "Flipkart", "Online Business", "GST Registration"],
    description: "Learn how to start and grow your online business on Amazon, Flipkart & Meesho.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Live seller account setup", "Product listing", "Business scaling"],
    stats: { duration: "1 Month", level: "Beginner", enrolled: "3,300+" },
    syllabus: ["Platform Overview", "Seller Account Setup", "Product Listing", "Orders & Returns", "/* TODO: More add karo */"],
    eligibility: ["Basic smartphone/computer skills"],
    features: ["Practical setup", "GST guidance", "Certificate", "Ongoing support"],
  },
  {
    id: 16,
    title: "AutoCAD & Civil Drafting",
    subtitle: "2D & 3D Drafting for Civil & Mechanical",
    category: "Design",
    level: "Intermediate",
    duration: "3 Months",
    students: 2700,
    rating: 4.5,
    reviews: 270,
    price: 5500,
    originalPrice: 8500,
    isFree: false,
    isPremium: true,
    badge: "",
    gradient: "grad-blue",
    icon: "📐",
    tags: ["AutoCAD", "Civil Drawing", "3D Modeling", "Drafting"],
    description: "Master AutoCAD for civil, mechanical and architectural drafting professionally.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Real project drawings", "Industry standard tools", "Job-ready skills"],
    stats: { duration: "3 Months", level: "Intermediate", enrolled: "2,700+" },
    syllabus: ["AutoCAD Interface", "2D Drawing", "3D Modeling", "Civil Plans", "/* TODO: More add karo */"],
    eligibility: ["Diploma/ITI in Civil/Mechanical preferred"],
    features: ["Software license", "Project files", "Certificate", "Job assistance"],
  },
  {
    id: 17,
    title: "Yoga & Wellness Instructor",
    subtitle: "Become a Certified Yoga Teacher",
    category: "Skill Development",
    level: "All Levels",
    duration: "3 Months",
    students: 1900,
    rating: 4.8,
    reviews: 190,
    price: 4000,
    originalPrice: 6000,
    isFree: false,
    isPremium: false,
    badge: "",
    gradient: "grad-teal",
    icon: "🧘",
    tags: ["Yoga", "Meditation", "Wellness", "Teaching"],
    description: "Learn yoga asanas, pranayama and become a certified wellness instructor.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Certified instructor training", "Practical yoga sessions", "Teaching methodology"],
    stats: { duration: "3 Months", level: "All Levels", enrolled: "1,900+" },
    syllabus: ["Yoga Basics", "Asanas", "Pranayama", "Meditation", "/* TODO: More add karo */"],
    eligibility: ["No prior yoga experience needed", "Age 16+"],
    features: ["Morning batches", "Mat provided", "Certificate", "Job placement in gyms"],
  },
  {
    id: 18,
    title: "Cybersecurity Fundamentals",
    subtitle: "Ethical Hacking & Online Safety Basics",
    category: "IT & Computer",
    level: "Advanced",
    duration: "3 Months",
    students: 1600,
    rating: 4.7,
    reviews: 160,
    price: 7000,
    originalPrice: 10000,
    isFree: false,
    isPremium: true,
    badge: "New",
    gradient: "grad-orange",
    icon: "🔐",
    tags: ["Cybersecurity", "Ethical Hacking", "Network Security", "Linux"],
    description: "Learn cybersecurity basics, ethical hacking and protect systems from attacks.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Hands-on lab practice", "Real attack simulations", "Security certifications prep"],
    stats: { duration: "3 Months", level: "Advanced", enrolled: "1,600+" },
    syllabus: ["Networking Basics", "Linux Fundamentals", "Ethical Hacking", "Web Security", "/* TODO: More add karo */"],
    eligibility: ["Basic networking knowledge", "Programming basics preferred"],
    features: ["Lab access", "Tools provided", "Certificate", "Industry mentors"],
  },
  {
    id: 19,
    title: "Hindi Spoken & Writing",
    subtitle: "Improve Hindi for Jobs & Daily Life",
    category: "Language",
    level: "Beginner",
    duration: "1 Month",
    students: 8500,
    rating: 4.3,
    reviews: 850,
    price: 1500,
    originalPrice: 2500,
    isFree: false,
    isPremium: false,
    badge: "",
    gradient: "grad-pink",
    icon: "🗒️",
    tags: ["Hindi Speaking", "Hindi Writing", "Grammar", "Govt. Exams"],
    description: "Improve Hindi communication skills for job interviews and government exams.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Speaking practice", "Grammar focus", "Exam preparation"],
    stats: { duration: "1 Month", level: "Beginner", enrolled: "8,500+" },
    syllabus: ["Hindi Grammar", "Reading", "Writing", "Speaking Practice", "/* TODO: More add karo */"],
    eligibility: ["Basic Hindi reading ability"],
    features: ["Daily sessions", "Practice material", "Certificate", "Exam tips"],
  },
  {
    id: 20,
    title: "Mobile Repairing Course",
    subtitle: "Smartphone Hardware & Software Repair",
    category: "Skill Development",
    level: "Beginner",
    duration: "2 Months",
    students: 4400,
    rating: 4.5,
    reviews: 440,
    price: 3000,
    originalPrice: 5000,
    isFree: false,
    isPremium: false,
    badge: "",
    gradient: "grad-green",
    icon: "📲",
    tags: ["Mobile Repair", "Hardware", "Software", "Entrepreneurship"],
    description: "Learn mobile phone hardware & software repair and start your own repair shop.",
    overview: "/* TODO: Full overview daalo */",
    highlights: ["Practical repair sessions", "Tools training", "Start your own shop"],
    stats: { duration: "2 Months", level: "Beginner", enrolled: "4,400+" },
    syllabus: ["Mobile Components", "Software Flashing", "Hardware Repair", "Shop Setup", "/* TODO: More add karo */"],
    eligibility: ["No prior experience needed", "Age 14+"],
    features: ["Tools provided", "Practical training", "Certificate", "Business guidance"],
  },
];
